# Generated by Django 5.1.3 on 2024-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20240408_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Refunded', 'Refunded')], default='New', max_length=10),
        ),
    ]
