# Generated by Django 5.1.3 on 2024-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight_total',
            field=models.FloatField(blank=True, default=400),
            preserve_default=False,
        ),
    ]
